;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32
lib_dir = lib_disabled

[common_settings]
build_flags = 
    -I include

[release_settings]
build_flags = 
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO

[dev_settings]
build_flags = 
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
    
[test_settings]
build_flags = 
    -D LOG_LOCAL_LEVEL=ESP_LOG_ERROR


[env]

[env:esp32]
platform = espressif32@6.12.0
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_upload.flash_size = 4MB
board_build.sdkconfig = sdkconfig.esp32
build_flags = 
    ${common_settings.build_flags}
    ${release_settings.build_flags}
monitor_speed = 115200 
monitor_raw = yes

[env:esp32_test]
extends = env:esp32
board_build.sdkconfig = sdkconfig.esp32_test
build_flags = 
    ${common_settings.build_flags}
    ${test_settings.build_flags}
monitor_speed = 115200 
test_speed = 115200
test_build_src = yes
test_filter = 
    embedded/network/wifi/*
    embedded/drivers/test_stepper_motion_plan
    embedded/protocol/test_web_command_ingest
    embedded/middleware/test_web_command_dispatcher
test_ignore = embedded/network/wifi/test_behavior

[env:esp32_clean_flash]
extends = env:esp32
targets =
    erase
    uploadfs
    upload

[env:native]
platform = native
test_framework = unity
build_flags =
    ${common_settings.build_flags}
test_build_src = no
test_filter =
    native/*

[env:native_coverage]
extends = env:native
build_flags =
    ${common_settings.build_flags}
    -O0
    -g
    --coverage
    -lgcov
build_unflags =
    -Os
test_filter =
    native/*
