#ifndef MYR_SELECTED_CONFIG_H
#define MYR_SELECTED_CONFIG_H

/*
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Copy this file to "LocalConfig.h" and only change values.
 * Keep the file structure and include guards as-is.
 */

/*  LocalConfig has been added to .gitignore to avoid accidental commiting of sensitive info such
    as your personal WiFi ssid and pass. DefaultConfig should only be changed if you intend on
    pushing your changes upstream.
*/

#ifndef SERVO
#define SERVO (1)
#endif
#ifndef STEPPER
#define STEPPER (0)
#endif
#ifndef BDC
#define BDC (0)
#endif

#define MYR_REMEMBER_CHANGES true   // If false, every boot will be as though it is the first time the device has started

#define MYR_DEVICE_DEFAULT_NAME "Motor"

/* #region Wifi Config */
#define MYR_WIFI_MODE_AP            0x0001
#define MYR_WIFI_MODE_STATION       0x0002
#define MYR_WIFI_MODE_AP_STATION    0x0004

#define MYR_WIFI_START_IN_MODE MYR_WIFI_MODE_AP
#define MYR_WIFI_MAINTAIN_AP false // If false the device will take down a running AP after it successfully connect to a station
#define MYR_WIFI_STA_TO_STA_FAILOVER_MODE MYR_WIFI_MODE_STATION // todo: what is this for
#define MYR_WIFI_SUPPORTED_MODES MYR_WIFI_MODE_AP | MYR_WIFI_MODE_STATION //Determines valid starting modes

#define MYR_WIFI_DEFAULT_AP_SSID_UID_CHAR_COUNT 4
#define MYR_WIFI_DEFAULT_AP_SSID "OpenMYR-Motor-"
#define MYR_WIFI_DEFAULT_AP_PASS ""

/*
 * Keep placeholders in DefaultConfig and define real values in LocalConfig.
 */
#define MYR_WIFI_DEFAULT_STATION_SSID "ssid"
#define MYR_WIFI_DEFAULT_STATION_PASS "pass"

#define MYR_WIFI_STATION_FAIL_TO_AP true // If the device fails to connect, should it establish an AP

#define MYR_WIFI_STATION_RETRIES 10 // How many times should the devce attempt to connect to a network before putting up an AP
#define MYR_WIFI_STA_RETRY_INTERVAL 1000 // Time in ms between attempts
#define MYR_WIFI_STA_RETRY_INTERVAL_LONG 15000 // Time in ms between attempts, after the AP is up
/* #endregion */

#endif // MYR_SELECTED_CONFIG_H
