#ifndef _DefaultConfig_H_ //Comment me out in LocalConfig
#define _DefailtConfig_H_ //Comment me out in LocalConfig

// #ifndef _LocalConfig_H_ //Uncomment me in LocalConfig
// #define _LocalConfig_H_ //Uncomment me in LocalConfig

#include <WString.h>
#include <string.h>

/*  DO NOT EDIT THIS FILE DIRECTLY, make a duplicate of this file and rename it to "LocalConfig.h".
    After duplicating, remove this comment and replace the ifndef on the top of the LocalConfig file.
*/

/*  LocalConfig has been added to .gitignore to avoid accidental commiting of sensitive info such
    as your personal WiFi ssid and pass. DefaultConfig should only be changed if you intend on 
    pushing your changes upstream.
*/

#ifndef SERVO
#define SERVO   (1)
#endif
#ifndef STEPPER
#define STEPPER (0)
#endif
#ifndef BDC
#define BDC     (0)
#endif

#define MYR_REMEMBER_CHANGES true   // If false, every boot will be as though it is the first time the device has started

const String MYR_DEVICE_DEFAULT_NAME = "Motor";

/* #region Wifi Config */ 
#define MYR_WIFI_MODE_AP            000001
#define MYR_WIFI_MODE_STATION       0x0002
#define MYR_WIFI_MODE_AP_STATION    0x0004

#define MYR_WIFI_START_IN_MODE MYR_WIFI_MODE_AP
#define MYR_WIFI_MAINTAIN_AP false // If false the device will take down a running AP after it successfully connect to a station
#define MYR_WIFI_STA_TO_STA_FAILOVER_MODE MYR_WIFI_MODE_STATION // 
#define MYR_WIFI_SUPPORTED_MODES MYR_WIFI_MODE_AP | MYR_WIFI_MODE_STATION //Determines valid starting modes

#define MYR_WIFI_DEFAULT_AP_SSID_UID_CHAR_COUNT 4

const String MYR_WIFI_DEFAULT_AP_SSID = "OpenMYR-Motor-";
const String MYR_WIFI_DEFAULT_AP_PASS = "";

const String MYR_WIFI_DEFAULT_STATION_SSID = "ssid";    //Do not define these in DefaultConfig.h, see warning above
const String MYR_WIFI_DEFAULT_STATION_PASS = "pass";

#define MYR_WIFI_STATION_FAIL_TO_AP 1  // If the device fails to connect, should it establish an AP

#define MYR_WIFI_STATION_RETRIES 10 // How many times should the devce attempt to connect to a network before putting up an AP
#define MYR_WIFI_STA_RETRY_INTERVAL 1000 // Time in ms between attempts
#define MYR_WIFI_STA_RETRY_INTERVAL_LONG 15000 // Time in ms between attempts, after the AP is up


#endif