idf_component_register(
    SRCS
        "app_main_idf.cpp"
        "../lib/protocols/WebServerUtils.cpp"
        "../lib/WiFi/WifiController.cpp"
        "../lib/generic/Lookup.cpp"
        "../lib/generic/FileIO.cpp"
        "../lib/Op/OpBuffer.cpp"
        "../lib/middleware/CommandLayer.cpp"
        "../lib/IoDrivers/PulseEngine.cpp"
        "../lib/IoDrivers/StepperDriver.cpp"
        "../lib/protocols/WebCommandDispatcher.cpp"
        "../lib/protocols/WebServer.cpp"
    INCLUDE_DIRS
        "../include"
        "../lib/WiFi"
        "../lib/generic"
        "../lib/Op"
        "../lib/middleware"
        "../lib/IoDrivers"
        "../lib/protocols"
    REQUIRES
        esp_http_server
        esp_event
        esp_netif
        esp_wifi
        nvs_flash
        littlefs
        json
        driver
        esp_timer
        app_update
        mbedtls
)
